apiVersion: v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 7
  template:
    metadata:
      labels:
        name: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: gcr.io/symmetric-ray-211101/nodeapp:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 50
